# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hangman.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import os

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 320, 781, 241))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.kb = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.kb.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.kb.setContentsMargins(0, 0, 0, 0)
        self.kb.setObjectName("kb")
        self.pushButton_26 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_26.sizePolicy().hasHeightForWidth())
        self.pushButton_26.setSizePolicy(sizePolicy)
        self.pushButton_26.setObjectName("pushButton_26")
        self.kb.addWidget(self.pushButton_26, 1, 3, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_17.sizePolicy().hasHeightForWidth())
        self.pushButton_17.setSizePolicy(sizePolicy)
        self.pushButton_17.setObjectName("pushButton_17")
        self.kb.addWidget(self.pushButton_17, 0, 11, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_18.sizePolicy().hasHeightForWidth())
        self.pushButton_18.setSizePolicy(sizePolicy)
        self.pushButton_18.setObjectName("pushButton_18")
        self.kb.addWidget(self.pushButton_18, 1, 10, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_19.sizePolicy().hasHeightForWidth())
        self.pushButton_19.setSizePolicy(sizePolicy)
        self.pushButton_19.setObjectName("pushButton_19")
        self.kb.addWidget(self.pushButton_19, 1, 1, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        self.pushButton_14.setObjectName("pushButton_14")
        self.kb.addWidget(self.pushButton_14, 0, 6, 1, 1)
        self.pushButton_25 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_25.sizePolicy().hasHeightForWidth())
        self.pushButton_25.setSizePolicy(sizePolicy)
        self.pushButton_25.setObjectName("pushButton_25")
        self.kb.addWidget(self.pushButton_25, 1, 4, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        self.pushButton_13.setObjectName("pushButton_13")
        self.kb.addWidget(self.pushButton_13, 0, 5, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_16.sizePolicy().hasHeightForWidth())
        self.pushButton_16.setSizePolicy(sizePolicy)
        self.pushButton_16.setObjectName("pushButton_16")
        self.kb.addWidget(self.pushButton_16, 0, 10, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setObjectName("pushButton_5")
        self.kb.addWidget(self.pushButton_5, 0, 4, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.kb.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_22.sizePolicy().hasHeightForWidth())
        self.pushButton_22.setSizePolicy(sizePolicy)
        self.pushButton_22.setObjectName("pushButton_22")
        self.kb.addWidget(self.pushButton_22, 1, 5, 1, 1)
        self.pushButton_24 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_24.sizePolicy().hasHeightForWidth())
        self.pushButton_24.setSizePolicy(sizePolicy)
        self.pushButton_24.setObjectName("pushButton_24")
        self.kb.addWidget(self.pushButton_24, 1, 9, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setObjectName("pushButton_3")
        self.kb.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setObjectName("pushButton_11")
        self.kb.addWidget(self.pushButton_11, 0, 7, 1, 1)
        self.pushButton_23 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_23.sizePolicy().hasHeightForWidth())
        self.pushButton_23.setSizePolicy(sizePolicy)
        self.pushButton_23.setObjectName("pushButton_23")
        self.kb.addWidget(self.pushButton_23, 1, 8, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_21.sizePolicy().hasHeightForWidth())
        self.pushButton_21.setSizePolicy(sizePolicy)
        self.pushButton_21.setObjectName("pushButton_21")
        self.kb.addWidget(self.pushButton_21, 1, 7, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setObjectName("pushButton_12")
        self.kb.addWidget(self.pushButton_12, 0, 8, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setObjectName("pushButton_4")
        self.kb.addWidget(self.pushButton_4, 0, 3, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_15.sizePolicy().hasHeightForWidth())
        self.pushButton_15.setSizePolicy(sizePolicy)
        self.pushButton_15.setObjectName("pushButton_15")
        self.kb.addWidget(self.pushButton_15, 0, 9, 1, 1)
        self.pushButton_27 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_27.sizePolicy().hasHeightForWidth())
        self.pushButton_27.setSizePolicy(sizePolicy)
        self.pushButton_27.setObjectName("pushButton_27")
        self.kb.addWidget(self.pushButton_27, 1, 2, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.kb.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_20 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_20.sizePolicy().hasHeightForWidth())
        self.pushButton_20.setSizePolicy(sizePolicy)
        self.pushButton_20.setObjectName("pushButton_20")
        self.kb.addWidget(self.pushButton_20, 1, 6, 1, 1)
        self.pushButton_32 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_32.sizePolicy().hasHeightForWidth())
        self.pushButton_32.setSizePolicy(sizePolicy)
        self.pushButton_32.setObjectName("pushButton_32")
        self.kb.addWidget(self.pushButton_32, 2, 7, 1, 1)
        self.pushButton_30 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_30.sizePolicy().hasHeightForWidth())
        self.pushButton_30.setSizePolicy(sizePolicy)
        self.pushButton_30.setObjectName("pushButton_30")
        self.kb.addWidget(self.pushButton_30, 2, 6, 1, 1)
        self.pushButton_33 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_33.sizePolicy().hasHeightForWidth())
        self.pushButton_33.setSizePolicy(sizePolicy)
        self.pushButton_33.setObjectName("pushButton_33")
        self.kb.addWidget(self.pushButton_33, 2, 5, 1, 1)
        self.pushButton_28 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_28.sizePolicy().hasHeightForWidth())
        self.pushButton_28.setSizePolicy(sizePolicy)
        self.pushButton_28.setObjectName("pushButton_28")
        self.kb.addWidget(self.pushButton_28, 2, 4, 1, 1)
        self.answer = QtWidgets.QLabel(self.centralwidget)
        self.answer.setGeometry(QtCore.QRect(0, 140, 800, 200))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.answer.setFont(font)
        self.answer.setAlignment(QtCore.Qt.AlignCenter)
        self.answer.setObjectName("answer")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuGame = QtWidgets.QMenu(self.menubar)
        self.menuGame.setObjectName("menuGame")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuPreferences = QtWidgets.QMenu(self.menuEdit)
        self.menuPreferences.setObjectName("menuPreferences")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Game = QtWidgets.QAction(MainWindow)
        self.actionNew_Game.setObjectName("actionNew_Game")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionUndo = QtWidgets.QAction(MainWindow)
        self.actionUndo.setObjectName("actionUndo")
        self.actionRedo = QtWidgets.QAction(MainWindow)
        self.actionRedo.setObjectName("actionRedo")
        self.actionFont = QtWidgets.QAction(MainWindow)
        self.actionFont.setObjectName("actionFont")
        self.actionFont_Colour = QtWidgets.QAction(MainWindow)
        self.actionFont_Colour.setObjectName("actionFont_Colour")
        self.menuGame.addAction(self.actionNew_Game)
        self.menuGame.addAction(self.actionSave)
        #self.menuPreferences.addAction(self.actionFont)
        #self.menuPreferences.addAction(self.actionFont_Colour)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        #self.menuEdit.addAction(self.menuPreferences.menuAction())
        self.menubar.addAction(self.menuGame.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        MainWindow.setWindowIcon(QtGui.QIcon(os.path.dirname(os.path.realpath(__file__))+os.path.sep+'hangman.png'))

        self.actionSave.triggered.connect(self.exitGame)
        self.actionNew_Game.triggered.connect(self.newGame)
        self.actionUndo.triggered.connect(self.undo)
        self.actionRedo.triggered.connect(self.redo)

        MainWindow.setStyleSheet("#MainWindow { border-image: url(f0.png) 0 0 0 0 stretch stretch; }")

        self.guessed = []
        self.undone = []
        self.lives = 5

        self.actionUndo.setEnabled(False)
        self.actionRedo.setEnabled(False)
        self.getWord()
        self.retranslateUi(MainWindow)
        self.setBlanks()
        
        self.pushButton.clicked.connect(lambda: self.check(self.pushButton))
        self.pushButton_2.clicked.connect(lambda: self.check(self.pushButton_2))
        self.pushButton_3.clicked.connect(lambda: self.check(self.pushButton_3))
        self.pushButton_4.clicked.connect(lambda: self.check(self.pushButton_4))
        self.pushButton_5.clicked.connect(lambda: self.check(self.pushButton_5))
        self.pushButton_11.clicked.connect(lambda: self.check(self.pushButton_11))
        self.pushButton_12.clicked.connect(lambda: self.check(self.pushButton_12))
        self.pushButton_13.clicked.connect(lambda: self.check(self.pushButton_13))
        self.pushButton_14.clicked.connect(lambda: self.check(self.pushButton_14))
        self.pushButton_15.clicked.connect(lambda: self.check(self.pushButton_15))
        self.pushButton_16.clicked.connect(lambda: self.check(self.pushButton_16))
        self.pushButton_17.clicked.connect(lambda: self.check(self.pushButton_17))
        self.pushButton_18.clicked.connect(lambda: self.check(self.pushButton_18))
        self.pushButton_19.clicked.connect(lambda: self.check(self.pushButton_19))
        self.pushButton_20.clicked.connect(lambda: self.check(self.pushButton_20))
        self.pushButton_21.clicked.connect(lambda: self.check(self.pushButton_21))
        self.pushButton_22.clicked.connect(lambda: self.check(self.pushButton_22))
        self.pushButton_23.clicked.connect(lambda: self.check(self.pushButton_23))
        self.pushButton_24.clicked.connect(lambda: self.check(self.pushButton_24))
        self.pushButton_25.clicked.connect(lambda: self.check(self.pushButton_25))
        self.pushButton_26.clicked.connect(lambda: self.check(self.pushButton_26))
        self.pushButton_27.clicked.connect(lambda: self.check(self.pushButton_27))
        self.pushButton_28.clicked.connect(lambda: self.check(self.pushButton_28))
        self.pushButton_30.clicked.connect(lambda: self.check(self.pushButton_30))
        self.pushButton_32.clicked.connect(lambda: self.check(self.pushButton_32))
        self.pushButton_33.clicked.connect(lambda: self.check(self.pushButton_33))

        self.btngroup = QtWidgets.QButtonGroup(MainWindow)
        self.btngroup.addButton(self.pushButton)
        self.btngroup.addButton(self.pushButton_2)
        self.btngroup.addButton(self.pushButton_3)
        self.btngroup.addButton(self.pushButton_4)
        self.btngroup.addButton(self.pushButton_5)
        self.btngroup.addButton(self.pushButton_11)
        self.btngroup.addButton(self.pushButton_12)
        self.btngroup.addButton(self.pushButton_13)
        self.btngroup.addButton(self.pushButton_14)
        self.btngroup.addButton(self.pushButton_16)
        self.btngroup.addButton(self.pushButton_17)
        self.btngroup.addButton(self.pushButton_18)
        self.btngroup.addButton(self.pushButton_19)
        self.btngroup.addButton(self.pushButton_20)
        self.btngroup.addButton(self.pushButton_21)
        self.btngroup.addButton(self.pushButton_22)
        self.btngroup.addButton(self.pushButton_23)
        self.btngroup.addButton(self.pushButton_24)
        self.btngroup.addButton(self.pushButton_25)
        self.btngroup.addButton(self.pushButton_26)
        self.btngroup.addButton(self.pushButton_27)
        self.btngroup.addButton(self.pushButton_28)
        self.btngroup.addButton(self.pushButton_30)
        self.btngroup.addButton(self.pushButton_15)
        self.btngroup.addButton(self.pushButton_32)
        self.btngroup.addButton(self.pushButton_33)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hangman"))
        self.pushButton_26.setText(_translate("MainWindow", "O"))
        self.pushButton_17.setText(_translate("MainWindow", "L"))
        self.pushButton_18.setText(_translate("MainWindow", "V"))
        self.pushButton_19.setText(_translate("MainWindow", "M"))
        self.pushButton_14.setText(_translate("MainWindow", "G"))
        self.pushButton_25.setText(_translate("MainWindow", "P"))
        self.pushButton_13.setText(_translate("MainWindow", "F"))
        self.pushButton_16.setText(_translate("MainWindow", "K"))
        self.pushButton_5.setText(_translate("MainWindow", "E"))
        self.pushButton.setText(_translate("MainWindow", "A"))
        self.pushButton_22.setText(_translate("MainWindow", "Q"))
        self.pushButton_24.setText(_translate("MainWindow", "U"))
        self.pushButton_3.setText(_translate("MainWindow", "C"))
        self.pushButton_11.setText(_translate("MainWindow", "H"))
        self.pushButton_23.setText(_translate("MainWindow", "T"))
        self.pushButton_21.setText(_translate("MainWindow", "S"))
        self.pushButton_12.setText(_translate("MainWindow", "I"))
        self.pushButton_4.setText(_translate("MainWindow", "D"))
        self.pushButton_15.setText(_translate("MainWindow", "J"))
        self.pushButton_27.setText(_translate("MainWindow", "N"))
        self.pushButton_2.setText(_translate("MainWindow", "B"))
        self.pushButton_20.setText(_translate("MainWindow", "R"))
        self.pushButton_32.setText(_translate("MainWindow", "Z"))
        self.pushButton_30.setText(_translate("MainWindow", "Y"))
        self.pushButton_33.setText(_translate("MainWindow", "X"))
        self.pushButton_28.setText(_translate("MainWindow", "W"))
        self.answer.setText(_translate("MainWindow", ""))
        self.menuGame.setTitle(_translate("MainWindow", "Game"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuPreferences.setTitle(_translate("MainWindow", "Preferences"))
        self.actionNew_Game.setText(_translate("MainWindow", "New Game"))
        self.actionNew_Game.setStatusTip(_translate("MainWindow", "End this game and start a new one"))
        self.actionNew_Game.setShortcut(_translate("MainWindow", "Ctrl+N"))
        self.actionSave.setText(_translate("MainWindow", "Close"))
        self.actionSave.setStatusTip(_translate("MainWindow", "Close the application"))
        self.actionSave.setShortcut(_translate("MainWindow", "Esc"))
        self.actionUndo.setText(_translate("MainWindow", "Undo"))
        self.actionUndo.setStatusTip(_translate("MainWindow", "Undo your last action"))
        self.actionUndo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.actionRedo.setText(_translate("MainWindow", "Redo"))
        self.actionRedo.setStatusTip(_translate("MainWindow", "Redo your last undo"))
        self.actionRedo.setShortcut(_translate("MainWindow", "Ctrl+Y"))
        self.actionFont.setText(_translate("MainWindow", "Font"))
        self.actionFont_Colour.setText(_translate("MainWindow", "Font Colour"))
        
    

    def getWord(self):
        self.msg = QtWidgets.QInputDialog(MainWindow)
        text, result = self.msg.getText(MainWindow, 'Welcome', 'Enter a word')

        if result:
            self.word = text.upper()
            MainWindow.setStyleSheet("#MainWindow { border-image: url(f1.png) 0 0 0 0 stretch stretch; }")
        else:
            sys.exit()
            

    def setBlanks(self):
        self.ans = []
        for i in self.word:
            if i not in [chr(i) for i in range(ord('A'),ord('Z')+1)]:
                self.ans.append(i)
            elif i == ' ':
                self.ans.append('  ')
            else:
                self.ans.append('_')
        self.answer.setText('  '.join(self.ans))

    def newGame(self):
        self.ans = []
        self.getWord()
        self.setBlanks()
        self.undone = []
        self.guessed = []
        self.lives = 5
        for btn in self.btngroup.buttons():
            btn.setEnabled(True)
        self.updatePic()
    
    def redo(self):
        if self.undone[-1] in self.word:
            for i in range(len(self.word)):
                if self.word[i] == self.undone[-1]:
                    self.ans[i] = self.undone[-1]
        for btn in self.btngroup.buttons():
            if self.undone[-1] == btn.text():
                btn.setEnabled(False)
        else:
            self.lives -= 1
        self.answer.setText('  '.join(self.ans))
        self.guessed.append(self.undone[-1])
        self.undone.pop(-1)
        if len(self.undone) == 0:
            self.actionRedo.setEnabled(False)
        self.actionUndo.setEnabled(True)
        
        self.updatePic()

    def undo(self):
        if self.guessed[-1] in self.ans:
            for i in range(len(self.ans)):
                if self.ans[i] == self.guessed[-1]:
                    self.ans[i] = '_'
        for btn in self.btngroup.buttons():
            if self.guessed[-1] == btn.text():
                btn.setEnabled(True)
        else:
            self.lives += 1
        self.actionRedo.setEnabled(True)
        self.undone.append(self.guessed[-1])
        self.guessed.pop(-1)
        self.answer.setText('  '.join(self.ans))
        if len(self.guessed) <= 0:
            self.actionUndo.setEnabled(False)
        
        self.updatePic()
        

    def check(self, n):
        n.setEnabled(False)
        if n.text() in self.word:
            for a in range(len(self.word)):
                if self.word[a] == n.text():
                    self.ans[a] = n.text()
        else:
            self.lives -= 1
        self.guessed.append(n.text())
        self.answer.setText('  '.join(self.ans))
        self.endDialog()
        self.undone = []
        if len(self.guessed) > 0:
            self.actionUndo.setEnabled(True)
        
        self.updatePic()

    def updatePic(self):
        if self.lives == 0:
            MainWindow.setStyleSheet("#MainWindow { border-image: url(f5.png) 0 0 0 0 stretch stretch; }")
        elif self.lives == 1:
            MainWindow.setStyleSheet("#MainWindow { border-image: url(f5.png) 0 0 0 0 stretch stretch; }")
        elif self.lives == 2:
            MainWindow.setStyleSheet("#MainWindow { border-image: url(f4.png) 0 0 0 0 stretch stretch; }")
        elif self.lives == 3:
            MainWindow.setStyleSheet("#MainWindow { border-image: url(f3.png) 0 0 0 0 stretch stretch; }")
        elif self.lives == 4:
            MainWindow.setStyleSheet("#MainWindow { border-image: url(f2.png) 0 0 0 0 stretch stretch; }")
        elif self.lives == 5:
            MainWindow.setStyleSheet("#MainWindow { border-image: url(f1.png) 0 0 0 0 stretch stretch; }")
            
    def endDialog(self):
        if '_' not in self.ans:
            self.end = QtWidgets.QMessageBox(MainWindow)
            self.end.setWindowTitle('Game Over')
            self.end.setText('You Won!')
            self.end.addButton(QtWidgets.QMessageBox.Close)
            self.end.addButton(QtWidgets.QPushButton('New Game'), self.end.ActionRole)
            if self.end.exec_() == 0:
                self.newGame()
            else:
                self.exitGame()
            self.actionUndo.setEnabled(False)
            self.actionRedo.setEnabled(False)
        elif self.lives == 0:
            self.end = QtWidgets.QMessageBox(MainWindow)
            self.end.setWindowTitle('Game Over')
            self.end.setText('You Lost! The word was '+self.word)
            self.end.addButton(QtWidgets.QMessageBox.Close)
            self.end.addButton(QtWidgets.QPushButton('New Game'), self.end.ActionRole)
            if self.end.exec_() == 0:
                self.newGame()
            else:
                self.exitGame()
            self.actionUndo.setEnabled(False)
            self.actionRedo.setEnabled(False)

    def exitGame(self):
        choice = QtWidgets.QMessageBox.question(MainWindow, 'Close', 'Close the application?', QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No)
        if choice == QtWidgets.QMessageBox.Yes:
            sys.exit()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
